version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: mysql_instance
    restart: always
    environment: 
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'dog'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
    - '3306:3306'
    volumes:
    - my-db:/var/lib/mysql
volumes:
  my-db:
